package httpserver

// ServiceNames lists World Monitor /api/{service}/... first path segment names (kebab-case),
// for GET /capabilities and service registry metadata.
var ServiceNames = []string{
	"aviation",
	"climate",
	"conflict",
	"consumer-prices",
	"cyber",
	"displacement",
	"economic",
	"forecast",
	"giving",
	"health",
	"imagery",
	"infrastructure",
	"intelligence",
	"leads",
	"maritime",
	"market",
	"military",
	"natural",
	"news",
	"positive-events",
	"prediction",
	"radiation",
	"research",
	"resilience",
	"sanctions",
	"scenario",
	"seismology",
	"shipping",
	"supply-chain",
	"thermal",
	"trade",
	"unrest",
	"webcam",
	"wildfire",
}
