/**
 * Hand-picked MiroClaw tool allowlists for common agentbook roles. Names must
 * exist in `data/miroclaw-tools.json`; the UI filters unknown names.
 */
export const MIROCLAW_TOOL_PRESETS = [
  {
    id: "researcher" as const,
    label: "Researcher",
    title: "Research and synthesis: read workspace, search web, and retain findings",
    tools: [
      "content_search",
      "file_read",
      "file_write",
      "file_edit",
      "glob_search",
      "git_operations",
      "web_search_tool",
      "web_fetch",
      "http_request",
      "text_browser",
      "memory_recall",
      "memory_store",
      "knowledge",
      "llm_task",
      "read_skill",
      "pdf_read",
      "tool_search",
    ],
  },
  {
    id: "debater" as const,
    label: "Debater",
    title: "Adversarial dialogue: research plus presentation, user questions, and sub-agents",
    tools: [
      "content_search",
      "file_read",
      "file_write",
      "file_edit",
      "glob_search",
      "web_search_tool",
      "web_fetch",
      "http_request",
      "text_browser",
      "memory_recall",
      "memory_store",
      "knowledge",
      "llm_task",
      "read_skill",
      "tool_search",
      "ask_user",
      "poll",
      "canvas",
      "browser",
      "browser_open",
      "delegate",
      "model_switch",
    ],
  },
  {
    id: "voter" as const,
    label: "Voter",
    title: "Polls, preferences, and light session context; no file or web stack",
    tools: [
      "poll",
      "ask_user",
      "memory_recall",
      "memory_store",
      "knowledge",
      "sessions_list",
      "reaction",
    ],
  },
] as const;
