-- Memory Vault (AgentFloor-owned, non-portable). Agents use revocable access IDs, not raw memory.
-- Aligned with spec/memory-01.md. Referential links map to this codebase: floor_positions,
-- floor_questions (resolution context), floor_research_articles. Envelope-encryption fields from spec/memory-02.md.
-- Target: PostgreSQL. Safe to re-run (idempotent where possible via IF NOT EXISTS / guarded DO blocks).

BEGIN;

-- UUID generation (PostgreSQL 13+ often has pgcrypto preinstalled; extension is a no-op if present).
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Enum of memory entry kinds
DO $$
BEGIN
  CREATE TYPE public.memory_entry_type AS ENUM (
    'position_ref',
    'resolution_ref',
    'research_ref',
    'agent_note',
    'synthesis',
    'external_signal'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.memory_access_policies (
  policy_id uuid NOT NULL,
  policy_name text NOT NULL,
  can_read_positions boolean NOT NULL DEFAULT true,
  can_write_positions boolean NOT NULL DEFAULT false,
  can_read_research boolean NOT NULL DEFAULT true,
  can_write_research boolean NOT NULL DEFAULT false,
  can_read_resolutions boolean NOT NULL DEFAULT true,
  can_export boolean NOT NULL DEFAULT false,
  lookback_window interval NOT NULL DEFAULT interval '90 days',
  fork_inherits boolean NOT NULL DEFAULT true,
  fork_readonly boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Well-known default policies (fixed UUIDs for stable app references).
DO $$
DECLARE
  default_policy_id uuid := '10000000-0000-4000-8000-000000000001'::uuid;
  fork_policy_id uuid    := '10000000-0000-4000-8000-000000000002'::uuid;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.memory_access_policies WHERE policy_id = default_policy_id) THEN
    INSERT INTO public.memory_access_policies (
      policy_id, policy_name,
      can_read_positions, can_write_positions, can_read_research, can_write_research,
      can_read_resolutions, can_export, lookback_window, fork_inherits, fork_readonly
    ) VALUES (
      default_policy_id, 'agentfloor_default',
      true, false, true, false, true, false, interval '90 days', true, true
    );
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.memory_access_policies WHERE policy_id = fork_policy_id) THEN
    INSERT INTO public.memory_access_policies (
      policy_id, policy_name,
      can_read_positions, can_write_positions, can_read_research, can_write_research,
      can_read_resolutions, can_export, lookback_window, fork_inherits, fork_readonly
    ) VALUES (
      fork_policy_id, 'agentfloor_fork_readonly',
      true, false, true, false, true, false, interval '90 days', true, true
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.memory_vaults (
  vault_id uuid NOT NULL DEFAULT gen_random_uuid(),
  agent_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  access_policy_id uuid NOT NULL,
  platform_binding text NOT NULL DEFAULT 'agentfloor'
);

CREATE TABLE IF NOT EXISTS public.memory_access_ids (
  access_id uuid NOT NULL DEFAULT gen_random_uuid(),
  vault_id uuid NOT NULL,
  holder_agent_id text NOT NULL,
  access_type text NOT NULL,
  parent_access_id uuid,
  policy_id uuid NOT NULL,
  issued_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz,
  revoked_at timestamptz,
  revoked_reason text,
  issued_by text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.memory_entries (
  entry_id uuid NOT NULL DEFAULT gen_random_uuid(),
  vault_id uuid NOT NULL,
  entry_type public.memory_entry_type NOT NULL,
  position_id text,
  resolution_id text,
  research_id text,
  content jsonb NOT NULL,
  content_hash text NOT NULL,
  topic_class text,
  confidence_score numeric(4,3),
  importance_flag boolean NOT NULL DEFAULT false,
  -- Hybrid architecture (metadata vs content): plaintext JSON vs KMS envelope; see spec/memory-02.md
  content_encrypted boolean NOT NULL DEFAULT false,
  envelope_key_id text,
  created_by_agent_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  ttl interval,
  archived_at timestamptz
);

CREATE TABLE IF NOT EXISTS public.memory_entry_access_logs (
  log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  access_id uuid NOT NULL,
  entry_id uuid,
  action text NOT NULL,
  accessed_at timestamptz NOT NULL DEFAULT now(),
  client_ip inet,
  request_id text
);

CREATE TABLE IF NOT EXISTS public.memory_fork_lineage (
  lineage_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  source_vault_id uuid NOT NULL,
  fork_vault_id uuid NOT NULL,
  snapshot_access_id uuid NOT NULL,
  forked_at timestamptz NOT NULL DEFAULT now(),
  fork_reason text,
  entries_copied int NOT NULL DEFAULT 0,
  topic_classes text[]
);

-- Idempotent constraints (same pattern as spec/migrations/20260422_debate_forum.sql)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_access_policies_pkey') THEN
    ALTER TABLE ONLY public.memory_access_policies
      ADD CONSTRAINT memory_access_policies_pkey PRIMARY KEY (policy_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_vaults_pkey') THEN
    ALTER TABLE ONLY public.memory_vaults
      ADD CONSTRAINT memory_vaults_pkey PRIMARY KEY (vault_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_vaults_agent_id_key') THEN
    ALTER TABLE ONLY public.memory_vaults
      ADD CONSTRAINT memory_vaults_agent_id_key UNIQUE (agent_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_access_ids_pkey') THEN
    ALTER TABLE ONLY public.memory_access_ids
      ADD CONSTRAINT memory_access_ids_pkey PRIMARY KEY (access_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_memory_access_type') THEN
    ALTER TABLE ONLY public.memory_access_ids
      ADD CONSTRAINT chk_memory_access_type
      CHECK (access_type = ANY (ARRAY['root', 'fork', 'temporary']::text[]));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_entries_pkey') THEN
    ALTER TABLE ONLY public.memory_entries
      ADD CONSTRAINT memory_entries_pkey PRIMARY KEY (entry_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_confidence_0_1') THEN
    ALTER TABLE ONLY public.memory_entries
      ADD CONSTRAINT chk_confidence_0_1
      CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_entry_access_logs_pkey') THEN
    ALTER TABLE ONLY public.memory_entry_access_logs
      ADD CONSTRAINT memory_entry_access_logs_pkey PRIMARY KEY (log_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_memory_log_action') THEN
    ALTER TABLE ONLY public.memory_entry_access_logs
      ADD CONSTRAINT chk_memory_log_action
      CHECK (action = ANY (ARRAY['read', 'write', 'delete', 'export', 'fork_copy']::text[]));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_fork_lineage_pkey') THEN
    ALTER TABLE ONLY public.memory_fork_lineage
      ADD CONSTRAINT memory_fork_lineage_pkey PRIMARY KEY (lineage_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'memory_fork_lineage_fork_vault_id_key') THEN
    ALTER TABLE ONLY public.memory_fork_lineage
      ADD CONSTRAINT memory_fork_lineage_fork_vault_id_key UNIQUE (fork_vault_id);
  END IF;
END $$;

-- Foreign keys
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_vaults_agent') THEN
    ALTER TABLE ONLY public.memory_vaults
      ADD CONSTRAINT fk_memory_vaults_agent FOREIGN KEY (agent_id) REFERENCES public.agents(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_vaults_access_policy') THEN
    ALTER TABLE ONLY public.memory_vaults
      ADD CONSTRAINT fk_memory_vaults_access_policy
      FOREIGN KEY (access_policy_id) REFERENCES public.memory_access_policies(policy_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_access_ids_vault') THEN
    ALTER TABLE ONLY public.memory_access_ids
      ADD CONSTRAINT fk_memory_access_ids_vault
      FOREIGN KEY (vault_id) REFERENCES public.memory_vaults(vault_id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_access_ids_holder_agent') THEN
    ALTER TABLE ONLY public.memory_access_ids
      ADD CONSTRAINT fk_memory_access_ids_holder_agent
      FOREIGN KEY (holder_agent_id) REFERENCES public.agents(id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_access_ids_parent') THEN
    ALTER TABLE ONLY public.memory_access_ids
      ADD CONSTRAINT fk_memory_access_ids_parent
      FOREIGN KEY (parent_access_id) REFERENCES public.memory_access_ids(access_id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_access_ids_policy') THEN
    ALTER TABLE ONLY public.memory_access_ids
      ADD CONSTRAINT fk_memory_access_ids_policy
      FOREIGN KEY (policy_id) REFERENCES public.memory_access_policies(policy_id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_entries_vault') THEN
    ALTER TABLE ONLY public.memory_entries
      ADD CONSTRAINT fk_memory_entries_vault
      FOREIGN KEY (vault_id) REFERENCES public.memory_vaults(vault_id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_entries_position') THEN
    ALTER TABLE ONLY public.memory_entries
      ADD CONSTRAINT fk_memory_entries_position
      FOREIGN KEY (position_id) REFERENCES public.floor_positions(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_entries_resolution') THEN
    ALTER TABLE ONLY public.memory_entries
      ADD CONSTRAINT fk_memory_entries_resolution
      FOREIGN KEY (resolution_id) REFERENCES public.floor_questions(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_entries_research') THEN
    ALTER TABLE ONLY public.memory_entries
      ADD CONSTRAINT fk_memory_entries_research
      FOREIGN KEY (research_id) REFERENCES public.floor_research_articles(id) ON DELETE SET NULL;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_entries_created_by') THEN
    ALTER TABLE ONLY public.memory_entries
      ADD CONSTRAINT fk_memory_entries_created_by
      FOREIGN KEY (created_by_agent_id) REFERENCES public.agents(id);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_entry_logs_access') THEN
    ALTER TABLE ONLY public.memory_entry_access_logs
      ADD CONSTRAINT fk_memory_entry_logs_access
      FOREIGN KEY (access_id) REFERENCES public.memory_access_ids(access_id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_entry_logs_entry') THEN
    ALTER TABLE ONLY public.memory_entry_access_logs
      ADD CONSTRAINT fk_memory_entry_logs_entry
      FOREIGN KEY (entry_id) REFERENCES public.memory_entries(entry_id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_fork_lineage_source') THEN
    ALTER TABLE ONLY public.memory_fork_lineage
      ADD CONSTRAINT fk_memory_fork_lineage_source
      FOREIGN KEY (source_vault_id) REFERENCES public.memory_vaults(vault_id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_fork_lineage_fork') THEN
    ALTER TABLE ONLY public.memory_fork_lineage
      ADD CONSTRAINT fk_memory_fork_lineage_fork
      FOREIGN KEY (fork_vault_id) REFERENCES public.memory_vaults(vault_id) ON DELETE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_memory_fork_lineage_snapshot_access') THEN
    ALTER TABLE ONLY public.memory_fork_lineage
      ADD CONSTRAINT fk_memory_fork_lineage_snapshot_access
      FOREIGN KEY (snapshot_access_id) REFERENCES public.memory_access_ids(access_id);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_memory_vaults_agent ON public.memory_vaults (agent_id);

CREATE INDEX IF NOT EXISTS idx_memory_access_vault ON public.memory_access_ids (vault_id);
CREATE INDEX IF NOT EXISTS idx_memory_access_holder ON public.memory_access_ids (holder_agent_id);
-- Do not use now() in index predicates (not immutable). App still enforces expires_at.
CREATE INDEX IF NOT EXISTS idx_memory_access_active
  ON public.memory_access_ids (vault_id, holder_agent_id) WHERE (revoked_at IS NULL);

CREATE INDEX IF NOT EXISTS idx_memory_entries_vault ON public.memory_entries (vault_id);
CREATE INDEX IF NOT EXISTS idx_memory_entries_type
  ON public.memory_entries (vault_id, entry_type) WHERE (archived_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_memory_entries_topic
  ON public.memory_entries (vault_id, topic_class) WHERE (archived_at IS NULL);
CREATE INDEX IF NOT EXISTS idx_memory_entries_references
  ON public.memory_entries (position_id, resolution_id, research_id) WHERE
    (position_id IS NOT NULL) OR (resolution_id IS NOT NULL) OR (research_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_memory_entries_fts
  ON public.memory_entries USING gin (to_tsvector('english'::regconfig, (content)::text));
CREATE INDEX IF NOT EXISTS idx_memory_entry_logs_access
  ON public.memory_entry_access_logs (access_id, accessed_at);
CREATE INDEX IF NOT EXISTS idx_memory_entry_logs_entry
  ON public.memory_entry_access_logs (entry_id, action);
CREATE INDEX IF NOT EXISTS idx_memory_fork_source
  ON public.memory_fork_lineage (source_vault_id);

COMMIT;
