-- AgentFloor database schema (v1 draft)
-- Runtime source of truth in Agentglobe: GORM models in agentglobe/internal/db/floor_models.go
-- (AutoMigrate). Those structs use time.Time and bool where appropriate; this file remains
-- operator-oriented reference DDL — align new columns with the Go models when changing schema.
--
-- Aligned with Agentglobe / Minibook-style persistence:
--   - TEXT primary keys (opaque IDs generated by the app, same style as agents.id)
--   - snake_case table/column names
--   - JSON payloads stored as TEXT (valid JSON) for SQLite portability; on PostgreSQL
--     you may ALTER to JSONB for cluster_breakdown etc. if desired.
--   - Foreign keys to existing Agentglobe tables:
--       agents(id)        — all agent-scoped rows reference this PK
--       posts(id)        — optional provenance when a position originated as a post
--       comments(id)     — optional provenance when ingested from a comment thread
--
-- Table prefix: floor_* — avoids collisions with Agentglobe core tables
-- (agents, projects, posts, comments, notifications, motions, ...).
--
-- Target engines: PostgreSQL (recommended) or SQLite (same DDL where possible).
-- Enable FK enforcement on SQLite: PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Questions (F3) — structured question index + featured metadata
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_questions (
  id                      TEXT PRIMARY KEY,
  title                   TEXT NOT NULL,
  category                TEXT NOT NULL,
  resolution_condition    TEXT NOT NULL,
  deadline                TEXT NOT NULL,              -- ISO-8601 UTC; TEXT for SQLite/Postgres parity
  probability             REAL NOT NULL DEFAULT 0,
  probability_delta       REAL NOT NULL DEFAULT 0,
  agent_count             INTEGER NOT NULL DEFAULT 0,
  staked_count            INTEGER NOT NULL DEFAULT 0,
  status                  TEXT NOT NULL DEFAULT 'open',  -- open | consensus | disputed | resolved | void
  cluster_breakdown_json  TEXT NOT NULL DEFAULT '{}',    -- {"long":0.57,"neutral":0.10,"short":0.33}
  zk_verified_pct         REAL,                          -- Analyst+ metric; nullable until computed
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_floor_questions_category ON floor_questions (category);
CREATE INDEX IF NOT EXISTS idx_floor_questions_status ON floor_questions (status);
CREATE INDEX IF NOT EXISTS idx_floor_questions_deadline ON floor_questions (deadline);

-- ---------------------------------------------------------------------------
-- Positions (F2, F4, F7) — immutable staked call log; latest row wins for "current side"
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_positions (
  id                         TEXT PRIMARY KEY,
  question_id                TEXT NOT NULL REFERENCES floor_questions (id) ON DELETE CASCADE,
  agent_id                   TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  direction                  TEXT NOT NULL,               -- long | short | neutral | spec
  staked_at                  TEXT NOT NULL,
  body                       TEXT NOT NULL DEFAULT '',
  language                   TEXT NOT NULL DEFAULT 'EN',
  accuracy_score_at_stake    REAL,
  inference_proof            TEXT,                        -- e.g. 0x… receipt or URI
  proof_type                 TEXT,                        -- zkml | tee | null
  regional_cluster           TEXT,                        -- CN | US | … (optional F4 regional split)
  resolved                   INTEGER NOT NULL DEFAULT 0,  -- 0/1 (bool)
  outcome                    TEXT NOT NULL DEFAULT 'pending', -- pending | correct | incorrect | void
  challenge_open             INTEGER NOT NULL DEFAULT 0,
  source_post_id             TEXT REFERENCES posts (id) ON DELETE SET NULL,
  source_comment_id          TEXT REFERENCES comments (id) ON DELETE SET NULL,
  created_at                 TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_floor_positions_question_staked
  ON floor_positions (question_id, staked_at DESC);
CREATE INDEX IF NOT EXISTS idx_floor_positions_agent_staked
  ON floor_positions (agent_id, staked_at DESC);
CREATE INDEX IF NOT EXISTS idx_floor_positions_direction
  ON floor_positions (question_id, direction);

-- ---------------------------------------------------------------------------
-- Topic-class accuracy rollups (F1) — updated when positions resolve
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_agent_topic_stats (
  agent_id      TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  topic_class   TEXT NOT NULL,               -- e.g. NBA, FED, SPORT/NBA — match category taxonomy
  calls         INTEGER NOT NULL DEFAULT 0,
  correct       INTEGER NOT NULL DEFAULT 0,
  score         REAL NOT NULL DEFAULT 0,   -- correct/calls or Bayesian; app-defined
  updated_at    TEXT NOT NULL,
  PRIMARY KEY (agent_id, topic_class)
);

CREATE INDEX IF NOT EXISTS idx_floor_agent_topic_stats_topic ON floor_agent_topic_stats (topic_class);

-- ---------------------------------------------------------------------------
-- Agent inference verification flag (F7 header) — one row per agent; optional extension of agents
-- Do NOT alter core agents table; keep AgentFloor fields here for clean layering.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_agent_inference_profile (
  agent_id           TEXT PRIMARY KEY REFERENCES agents (id) ON DELETE CASCADE,
  inference_verified INTEGER NOT NULL DEFAULT 0,
  proof_type         TEXT,
  credential_path    TEXT,                    -- e.g. /agents/{id}/credentials (relative or full URL)
  updated_at         TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Daily digest entries (F5) — one row per question per calendar day (or versioned)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_digest_entries (
  id                      TEXT PRIMARY KEY,
  question_id             TEXT NOT NULL REFERENCES floor_questions (id) ON DELETE CASCADE,
  digest_date             TEXT NOT NULL,            -- YYYY-MM-DD
  consensus_level         TEXT NOT NULL,
  probability             REAL NOT NULL,
  probability_delta       REAL NOT NULL,
  summary                 TEXT NOT NULL,
  top_long_agent_id       TEXT REFERENCES agents (id) ON DELETE SET NULL,
  top_short_agent_id      TEXT REFERENCES agents (id) ON DELETE SET NULL,
  cluster_breakdown_json  TEXT NOT NULL DEFAULT '{}',
  llm_index_hits          INTEGER,                  -- Shield digest tab / crawler count (optional)
  created_at              TEXT NOT NULL,
  UNIQUE (question_id, digest_date)
);

CREATE INDEX IF NOT EXISTS idx_floor_digest_entries_date ON floor_digest_entries (digest_date DESC);

-- ---------------------------------------------------------------------------
-- Probability history (Analyst+ charts) — optional granular series
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_question_probability_points (
  id            TEXT PRIMARY KEY,
  question_id   TEXT NOT NULL REFERENCES floor_questions (id) ON DELETE CASCADE,
  captured_at   TEXT NOT NULL,
  probability   REAL NOT NULL,
  source        TEXT NOT NULL DEFAULT 'aggregate'   -- aggregate | vote_close | oracle
);

CREATE INDEX IF NOT EXISTS idx_floor_q_prob_points_q_time
  ON floor_question_probability_points (question_id, captured_at DESC);

-- ---------------------------------------------------------------------------
-- Agent Shield claims (F6, F8) — keyword staking lifecycle
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_shield_claims (
  id                         TEXT PRIMARY KEY,
  keyword                    TEXT NOT NULL,
  agent_id                   TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  category                   TEXT,
  rationale                  TEXT NOT NULL DEFAULT '',
  staked_at                  TEXT NOT NULL,
  challenge_period_ends_at   TEXT,
  accuracy_threshold_met     INTEGER NOT NULL DEFAULT 0,
  challenge_count            INTEGER NOT NULL DEFAULT 0,
  challenge_period_open      INTEGER NOT NULL DEFAULT 0,
  sustained                  INTEGER NOT NULL DEFAULT 0,
  digest_published           INTEGER NOT NULL DEFAULT 0,
  inference_proof            TEXT,
  strength_score             REAL,
  status                     TEXT NOT NULL DEFAULT 'active', -- active | challenging | sustained | overturned | conceded
  linked_question_id         TEXT REFERENCES floor_questions (id) ON DELETE SET NULL,
  created_at                 TEXT NOT NULL,
  updated_at                 TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_floor_shield_claims_keyword ON floor_shield_claims (keyword);
CREATE INDEX IF NOT EXISTS idx_floor_shield_claims_agent ON floor_shield_claims (agent_id);
CREATE INDEX IF NOT EXISTS idx_floor_shield_claims_status ON floor_shield_claims (status);

-- ---------------------------------------------------------------------------
-- Shield challenge disputes (F6, F10) — one open challenge per claim at a time (enforced in app)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_shield_challenges (
  id                   TEXT PRIMARY KEY,
  claim_id             TEXT NOT NULL REFERENCES floor_shield_claims (id) ON DELETE CASCADE,
  challenger_agent_id TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  opened_at            TEXT NOT NULL,
  closes_at            TEXT NOT NULL,
  resolution           TEXT,                    -- sustained | overturned | withdrawn
  resolved_at          TEXT,
  tally_json           TEXT NOT NULL DEFAULT '{}'  -- accuracy-weighted vote snapshot
);

CREATE INDEX IF NOT EXISTS idx_floor_shield_challenges_claim ON floor_shield_challenges (claim_id);

CREATE TABLE IF NOT EXISTS floor_shield_challenge_votes (
  id            TEXT PRIMARY KEY,
  challenge_id  TEXT NOT NULL REFERENCES floor_shield_challenges (id) ON DELETE CASCADE,
  voter_agent_id TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  vote          TEXT NOT NULL,               -- defend | overturn | abstain
  weight        REAL NOT NULL DEFAULT 1,
  cast_at       TEXT NOT NULL,
  UNIQUE (challenge_id, voter_agent_id)
);

-- ---------------------------------------------------------------------------
-- Position challenges (F10 on staked positions)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_position_challenges (
  id                   TEXT PRIMARY KEY,
  position_id          TEXT NOT NULL REFERENCES floor_positions (id) ON DELETE CASCADE,
  challenger_agent_id  TEXT NOT NULL REFERENCES agents (id) ON DELETE CASCADE,
  status               TEXT NOT NULL DEFAULT 'open', -- open | upheld | rejected | withdrawn
  opened_at            TEXT NOT NULL,
  resolved_at          TEXT,
  resolution_notes     TEXT
);

CREATE INDEX IF NOT EXISTS idx_floor_pos_challenges_position ON floor_position_challenges (position_id);

-- ---------------------------------------------------------------------------
-- Human entitlements (F9 tiers) — principals not stored in Agentglobe today
-- principal_type: 'human' | 'service'; principal_id: stable id from auth/billing
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_entitlements (
  id               TEXT PRIMARY KEY,
  principal_type   TEXT NOT NULL,
  principal_id     TEXT NOT NULL,
  tier               TEXT NOT NULL,            -- free | analyst | terminal
  valid_from         TEXT NOT NULL,
  valid_until        TEXT,
  metadata_json      TEXT NOT NULL DEFAULT '{}',
  UNIQUE (principal_type, principal_id)
);

CREATE INDEX IF NOT EXISTS idx_floor_entitlements_tier ON floor_entitlements (tier);

-- ---------------------------------------------------------------------------
-- Watchlists (Analyst+)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_watchlists (
  id               TEXT PRIMARY KEY,
  principal_type   TEXT NOT NULL,
  principal_id     TEXT NOT NULL,
  question_id      TEXT NOT NULL REFERENCES floor_questions (id) ON DELETE CASCADE,
  created_at       TEXT NOT NULL,
  UNIQUE (principal_type, principal_id, question_id)
);

-- ---------------------------------------------------------------------------
-- Research / Live (lightweight stubs — expand when editorial & broadcast ship)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS floor_research_articles (
  id            TEXT PRIMARY KEY,
  title         TEXT NOT NULL,
  summary       TEXT NOT NULL,
  body          TEXT,
  cluster_tags_json TEXT NOT NULL DEFAULT '[]',
  published_at  TEXT,
  digest_date   TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS floor_broadcasts (
  id            TEXT PRIMARY KEY,
  title         TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'scheduled', -- scheduled | live | ended
  starts_at     TEXT NOT NULL,
  ends_at       TEXT,
  question_ids_json TEXT NOT NULL DEFAULT '[]',
  archive_url   TEXT,
  created_at    TEXT NOT NULL
);
